---
title: "Geography 176A"
author: "[Jacob Braslaw](https://jacobbraslaw.github.io/)"
subtitle: "Lab 05: Tessalations"
date: "8/26/2020"
output: html_document
---

```{r, echo=FALSE}
library(raster) # Raster Data handling
library(tidyverse) # Data Manipulation
library(getlandsat) # keyless Landsat data (2013-2017)
library(sf) # Vector data processing
library(mapview)
library(osmdata)
```
```{r}
bb<-read_csv("../data/uscities.csv")%>% 
 filter(city == "Palo") %>% 
 st_as_sf(coords= c("lng", "lat"), crs= 4326) %>% 
  st_transform(5070) %>% 
  st_buffer(5000) %>% 
  st_bbox %>% 
  st_as_sfc() %>%
  st_as_sf()

mapview(bb) + osm$osm_polygons
library(leaflet)
leaflet() %>% 
  addTiles() %>%  
  addPolygons(data = osm$osm_polygons)

bbwgs<- bb %>% 
  st_transform(4326)
bb = st_bbox(bbwgs)

osm<- osmdata::opq(bbwgs) %>% 
  add_osm_feature("building") %>% 
  osmdata_sf()

mapview(osm$osm_polygons)  #not sure why this is not loading
```


```{r}
scenes<- lsat_scenes()
 
down<- scenes %>% 
  filter(min_lat<= bb$ymin, max_lat >= bb$ymax) %>% 
  filter(min_lon<= bb$xmin, max_lon>= bb$xmax) %>% 
  filter(as.Date(acquisitionDate) == as.Date("2016-09-26"))

write.csv(down, file = "../data/palo_flood.csv")

meta= read_csv(file = "../data/palo_flood.csv")

meta$download_url

files<- lsat_scene_files(meta$download_url) %>% 
  filter(grepl(paste0("B", 1:6, ".TIF$", collapse = "|"), file)) %>% 
  arrange(file) %>% 
  pull(file)



st= sapply(files, lsat_image)

s<- stack(st) %>% setNames(c(paste0("band", 1:6)))

cropper<- bbwgs %>% st_transform(crs(s))

r= crop(s, cropper)

par(mfrow= c(1,2))
plotRGB(r, r = 4, g= 3, b=2, stretch="hist")
plotRGB(r, r= 5, g= 4, b=3)

dev.off()

ndvi = (r$band5 - r$band4) / (r$band5 + r$band4)
plot(ndvi)

palette = colorRampPalette(c("blue", "white", "red"))

plot(ndvi, col= palette(256))

thresholding<- function(x){ifelse(x<=0, 1, NA)}

flood = calc(ndvi, thresholding)

plot(flood, col= "blue")

mapview(flood)
```

